blog_cbv/apps/accounts/urls.py
from django.urls import path

from apps.accounts.views import ProfileUpdateView, ProfileDetailView, UserRegistrationView, UserLoginView, \
    UserLogoutView

app_name='accounts'
urlpatterns=[
    path('user/edit/',ProfileUpdateView.as_view(),name='profile_edit'),
    path('register/',UserRegistrationView.as_view(),name='register'),
    path('login/',UserLoginView.as_view(),name='login'),
    path('logout/',UserLogoutView.as_view(),name='logout'),
    path('user/<slug:slug>/',ProfileDetailView.as_view(),name='profile_detail'),
]

blog_cbv/blog_cbv/urls.py
from django.contrib import admin
from django.urls import path, include

from apps.blog.feeds import LatestPostsFeed
from blog_cbv import settings
from django.conf.urls.static import static
import apps.blog.urls

handler403 = 'apps.blog.views.tr_handler403'
handler404 = 'apps.blog.views.tr_handler404'
handler500 = 'apps.blog.views.tr_handler500'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('feeds/latest/', LatestPostsFeed(), name='latest_post_feed'),
    path('', include('apps.blog.urls', namespace='blog')),
    path('', include('apps.accounts.urls', namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include('debug_toolbar.urls')),
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog_cbv/apps/accounts/models.py
from django.core.cache import cache
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from django.db import models

from apps.services.utils import unique_slugify


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField(verbose_name="URL", max_length=255, blank=True)
    avatar = models.ImageField(
        verbose_name='Фотография профиля',
        upload_to='images/avatars/%Y/%m/%d/',
        default='images/avatars/default.jpg',
        validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])],
        blank=True,
    )
    bio = models.TextField(verbose_name='Биография', blank=True, max_length=500)
    birth_day = models.DateField(verbose_name='Дата рождения', blank=True, null=True)

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'
        ordering = ['user']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, self.user.username, self.slug)
        super(Profile, self).save(*args, **kwargs)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('accounts:profile_detail', kwargs={'slug': self.slug})

    def is_online(self):
        cache_key = f'last-seen-{self.user.id}'
        last_seen = cache.get(cache_key)

        if last_seen is not None:
            return True
        return False



class Project(models.Model):
    name=models.CharField(verbose_name="Название проекта",help_text="Введите название проекта",max_length=200)
    start_date=models.DateField(verbose_name="Дата начала проекта",help_text="Укажите дату начала проекта")
    end_date=models.DateField(verbose_name="Дата окончания проекта",help_text="Укажите дату окончания проекта")
    budget=models.DecimalField(verbose_name="Бюджет проекта",help_text="Введите бюджет проекта",max_digits=12,decimal_places=2)
    progress=models.PositiveSmallIntegerField(verbose_name="Процент выполнения",help_text="Введите процент выполнения проекта")
    description=models.TextField(verbose_name="Описание проекта",help_text="Введите описание проекта")
    is_completed=models.BooleanField(verbose_name="Проект завершён",help_text="Укажите, завершён ли проект",default=False)
    repository_url=models.URLField(verbose_name="URL репозитория",help_text="Введите URL репозитория проекта")
    manager=models.CharField(verbose_name="Менеджер проекта",help_text="Введите имя менеджера проекта",max_length=50)
    slug=models.SlugField(verbose_name="Слаг проекта",help_text="Введите слаг проекта",max_length=255,unique=True)

blog_cbv/apps/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django_recaptcha.fields import ReCaptchaField

from apps.accounts.models import Profile


class UserUpdateForm(forms.ModelForm):
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control mb-1'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control mb-1'}))
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control mb-1'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control mb-1'}))

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and User.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError('Email адрес должен быть уникальным')
        return email


class ProfileUpdateForm(forms.ModelForm):
    birth_day = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control mb-1'}))
    bio = forms.CharField(widget=forms.Textarea(attrs={'rows': 5, 'class': 'form-control mb-1'}))
    avatar = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control mb-1'}))

    class Meta:
        model = Profile
        fields = ('bio', 'birth_day', 'avatar')


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model=get_user_model()
        fields = ['username', 'password1', 'password2', 'email', 'first_name', 'last_name']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and User.objects.filter(email=email).exists():  # exlude добавлять в случае обновления
            raise forms.ValidationError('Пользователь с таким email уже существует.')
        return email

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({"placeholder": "Придумайте свой логин"})
        self.fields['password1'].widget.attrs.update({"placeholder": "Придумайте свой пароль"})
        self.fields['password2'].widget.attrs.update({"placeholder": "Повторите придуманный пароль"})
        self.fields['email'].widget.attrs.update({"placeholder": "Введите свой email"})
        self.fields['first_name'].widget.attrs.update({"placeholder": "Ваше имя"})
        self.fields['last_name'].widget.attrs.update({"placeholder": "Ваша фамилия"})
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control", "autocomplete": "off"})


class UserLoginForm(AuthenticationForm):

    recaptcha = ReCaptchaField()

    class Meta:
        model=get_user_model()
        fields=['username', 'password','recaptcha']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Логин пользователя'
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['placeholder'] = 'Пароль пользователя'
        self.fields['password'].widget.attrs['class'] = 'form-control'
        self.fields['username'].label = 'Логин'

blog_cbv/apps/accounts/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.db import transaction
from django.urls import reverse_lazy
from django.views.generic import DetailView, UpdateView, CreateView

from apps.accounts.forms import ProfileUpdateForm, UserUpdateForm, UserRegistrationForm, UserLoginForm
from apps.accounts.models import Profile


class ProfileDetailView(DetailView):
    model = Profile
    context_object_name = 'profile'
    template_name = 'accounts/profile_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Профиль пользователя {self.request.user.username}'
        return context


class ProfileUpdateView(UpdateView):
    template_name = 'accounts/profile_edit.html'
    model = Profile
    form_class = ProfileUpdateForm

    def get_object(self, queryset=None):
        return self.request.user.profile

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['title']=f'Редактирование профиля пользователя: {self.request.user.username}'
        if self.request.POST:
            context['user_form']=UserUpdateForm(self.request.POST,instance=self.request.user)
        else:
            context['user_form']=UserUpdateForm(instance=self.request.user)
        return context

    def form_valid(self,form):#form-та форма что явно указана в get_form_class
        context=self.get_context_data()#контекст в первую очередь словарь
        user_form=context['user_form']
        with transaction.atomic():
            if all([form.is_valid(), user_form.is_valid()]):
                form.save()
                user_form.save()
            else:
                context.update({'user_form':user_form})#обновляем чтобы отобразить ошибки и сохр уже ранее введ данные
                return self.render_to_response(context)#ренедерим чтобы показать ошибки валидации
        return super().form_valid(form)

    def get_success_url(self):#тут object так как ссылаемся на только что обновл или созд объект
        return reverse_lazy('accounts:profile_detail',kwargs={'slug':self.object.slug})


class UserRegistrationView(SuccessMessageMixin,CreateView):
    template_name = 'accounts/user_register.html'
    form_class=UserRegistrationForm
    success_url = reverse_lazy('blog:post_list')
    success_message = 'Вы успешно зарегистрировались. Можете войти на сайт!'

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['title']='Регистрация пользователя'
        return context


class UserLoginView(SuccessMessageMixin,LoginView):
    template_name = 'accounts/user_login.html'
    form_class = UserLoginForm
    success_message = 'Добро пожаловать на сайт!'
    next_page = 'blog:post_list'

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['title']='Авторизация пользователя'
        return context

class UserLogoutView(LogoutView):
    next_page = 'blog:post_list'

blog_cbv/templates/accounts/profile_detail.html
{% extends 'main.html' %}

{% block content %}
<div class="card border-0">
        <div class="card-body">
            <div class="row">
                <div class="col-md-3">
                    <figure>
                        <img src="{{ profile.avatar.url }}" class="img-fluid rounded-0" alt="{{ profile }}">
                    </figure>
                </div>
                <div class="col-md-9">
                     <h5 class="card-title">
                        {{ profile }}
                    </h5>
                    <div class="card-text">
                        <ul>
                            <li>Никнейм: {{ profile.user.username }}</li>
                            {% if profile.user.get_full_name %} <li>Имя и фамилия: {{ profile.user.get_full_name }}</li> {% endif %}
                            <li>Заходил: {{ profile.user.last_login }}| {% if profile.is_online %}Онлайн{% else %}Не в сети {% endif %} </li> 
                            <li>Дата рождения: {{ profile.birth_day }}</li>
                            <li>О себе: {{ profile.bio }}</li>
                        </ul>
                    {% if request.user == profile.user %} <a href="{% url 'accounts:profile_edit' %}" class="btn btn-sm btn-primary">Редактировать профиль</a> {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog_cbv/templates/accounts/profile_edit.html
{% extends 'main.html' %}

{% block content %}
<div class="card mb-3 border-0 nth-shadow">
   <div class="card-body">
      <div class="card-title nth-card-title">
         <h4>Изменение профиля</h4>
      </div>
      <form method="post" enctype="multipart/form-data">
         {% csrf_token %}
         {{ user_form.as_p }}
         {{ form.as_p }}
         <div class="d-grid gap-2 d-md-block mt-2">
            <button type="submit" class="btn btn-dark">Подтвердить изменение профиля</button>
         </div>
      </form>
   </div>
</div>
{% endblock %}

blog_cbv/templates/accounts/user_login.html
{% extends 'main.html' %}

{% block content %}
    <div class="card mb-3 border-0 nth-shadow">
        <div class="card-body">
            <div class="card-title nth-card-title">
                <h4>Авторизация на сайте</h4>
            </div>
            <form method="post" action="{% url 'accounts:login' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="d-grid gap-2 d-md-block mt-2">
                <button type="submit" class="btn btn-dark">Авторизоваться</button>
             </div>
            </form>
        </div>
    </div>
{% endblock %}

blog_cbv/templates/accounts/user_register.html
{% extends 'main.html' %}

{% block content %}
    <div class="card mb-3 border-0 nth-shadow">
        <div class="card-body">
            <div class="card-title nth-card-title">
                <h4>Регистрация на сайте</h4>
            </div>
            <form method="post" action="{% url 'accounts:register' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-dark mt-2">Зарегистрироваться</button>
            </form>
        </div>
    </div>
{% endblock %}