blog_cbv/apps/accounts/urls.py
from django.urls import path

from apps.accounts.views import ProfileUpdateView, ProfileDetailView, UserRegistrationView, UserLoginView, \
    UserLogoutView

app_name='accounts'
urlpatterns=[
    path('user/edit/',ProfileUpdateView.as_view(),name='profile_edit'),
    path('register/',UserRegistrationView.as_view(),name='register'),
    path('login/',UserLoginView.as_view(),name='login'),
    path('logout/',UserLogoutView.as_view(),name='logout'),
    path('user/<slug:slug>/',ProfileDetailView.as_view(),name='profile_detail'),
]

blog_cbv/apps/blog/urls.py
from django.urls import path

app_name='blog'
from apps.blog.views import PostListView, PostDetailView, PostFromCategoryView, CreatePostView, PostUpdateView, \
    CommentCreateView, PostByTagListView, RatingCreateView

urlpatterns=[
    path('', PostListView.as_view(), name='post_list'),
    path('post/create/', CreatePostView.as_view(), name='create_post'),
    path('rating/',RatingCreateView.as_view(), name='rating'),
    path('post/<int:pk>/comments/create/', CommentCreateView.as_view(), name='comment_create_view'),
    path('post/<slug:slug>/update/',PostUpdateView.as_view(), name='update_post'),
    path('post/<slug:slug>/',PostDetailView.as_view(),name='post_detail'),
    path('post/tags/<slug:tag>/', PostByTagListView.as_view(), name='post_by_tag'),
    path('category/<slug:slug>/',PostFromCategoryView.as_view(),name='post_by_category'),
]

blog_cbv/blog_cbv/urls.py
from django.contrib import admin
from django.urls import path, include

from apps.blog.feeds import LatestPostsFeed
from blog_cbv import settings
from django.conf.urls.static import static
import apps.blog.urls

handler403 = 'apps.blog.views.tr_handler403'
handler404 = 'apps.blog.views.tr_handler404'
handler500 = 'apps.blog.views.tr_handler500'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('feeds/latest/', LatestPostsFeed(), name='latest_post_feed'),
    path('', include('apps.blog.urls', namespace='blog')),
    path('', include('apps.accounts.urls', namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include('debug_toolbar.urls')),
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog_cbv/templates/footer.html
<footer class="py-5 bg-dark mt-2 mt-auto">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023, Powered by
        Django</p></div>
</footer>

blog_cbv/templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'blog:post_list' %}">My Django Blog 2.0</a>
        </div>
</nav>
<div class='d-flex justify-content-end '>
            {% if request.user.is_authenticated %}
        <div class="dropdown text-end">
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            {{ request.user }}
          </a>
          <ul class="dropdown-menu text-small">
            <li><a class="dropdown-item" href="{% url 'blog:create_post' %}">Добавить статью</a></li>
            <li><a class="dropdown-item" href="{% url 'accounts:profile_detail' request.user.profile.slug %}">Мой профиль</a></li>
            <li><hr class="dropdown-divider"></li>
            <li>
                    <form action="{% url 'accounts:logout' %}" method="post">{% csrf_token %}
                        <a href="#" class="dropdown-item" onclick="parentNode.submit();">Log Out</a>
                    </form>
            </li>
          </ul>
        </div>
        {% else %}
            <ul class="nav ">
              <li><a href="{% url 'accounts:register' %}" class="nav-link px-2 link-secondary">Регистрация</a></li>
              <li><a href="{% url 'accounts:login' %}" class="nav-link px-2 link-dark">Вход</a></li>
            </ul>
        {% endif %}
</div>

blog_cbv/templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    {% load django_bootstrap5 %}
    <meta charset="UTF-8">
    <title>{{ title}}</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <script  defer src="{% static 'js/bootstrap.js' %}"></script>
    {{ form.media }}
</head>
<body class="d-flex flex-column min-vh-100">
{% include 'header.html' %}
<div class="container">
    <div class="row">
        <div class="col-lg-8 p-4">
            {% include 'includes/messages.html' %}
            {% block content %}
            {% endblock %}
            {% include 'pagination.html' %}
        </div>
        <div class="col-4 p-4">
            {% include 'sidebar.html' %}
        </div>
    </div>
</div>
{% include 'footer.html' %}
<script src="{% static 'js/backend.js' %}"></script>
{% block script %}{% endblock %}
</body>
</html>

blog_cbv/templates/pagination.html
{% if is_paginated %}
    <div class="pagination p-3">
    {% for page_number in page_obj.paginator.get_elided_page_range %}
        {% if page_number == page_obj.paginator.ELLIPSIS %}
            {{page_number}}
        {% else %}
            <a href="?page={{ page_number }}" class="page-link">
                {{page_number}}
            </a>
        {% endif %}
    {% endfor %}
    </div>
{%endif%}

blog_cbv/templates/sidebar.html
{% load mptt_tags %}

<div class="card mb-4">
    <div class="card-header">Categories</div>
    <div class="card-body ">
        {% full_tree_for_model blog.Category as categories %}
        <ul>
            {% recursetree categories %}
                <li>
                    <a href="{{ node.get_absolute_url }}">{{ node.title }}</a>
                </li>

                {% if not node.is_leaf_node %}
                    <ul>
                        {{ children }}
                    </ul>
                {% endif %}
            {% endrecursetree %}
        </ul>
    </div>
</div>
<a href="{% url 'latest_post_feed' %}">Подписаться на RSS ленту</a>