mysite/accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
import accounts.views as views

app_name='accounts'

urlpatterns=[
    path('signup/',views.SignUpView.as_view(), name='signup'),
    path('login',views.CustomLoginView.as_view(redirect_authenticated_user=True,#авториз пользователь не сможет на стр входа
                                         template_name='registration/login.html'),
                                         name='login'),
    path('logout/',LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('profile/',views.profile, name='profile'),
    path('change_password/',views.ChangePasswordView.as_view(), name='change_password'),
]

mysite/blog/urls.py
from django.urls import path
from blog import views

app_name='blog'

urlpatterns=[
    path('',views.post_list,name='post_list'),
    path('search/', views.post_search, name='post_search'),
    path('<slug:tag_slug>/',views.post_list,name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.post_detail,name='post_detail'),
    path('<int:post_id>/share/',views.share_post,name='share_post'),
    path('<int:post_id>/comment/',views.post_comment,name='post_comment'),
]

mysite/mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import accounts.urls
import blog.urls
from django.contrib.sitemaps.views import sitemap

import blog_api.urls
from blog.sitemaps import PostSitemap
from mysite import settings

sitemaps = {
    'sites': PostSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include(blog.urls, namespace='blog')),
    path('accounts/', include(accounts.urls, namespace='accounts')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('api/', include(blog_api.urls)),
    path("api-auth/", include("rest_framework.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(
            status=Post.Status.PUBLISHED)  # переопределяем базовую логику ф-ции(super..)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Drafts'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(unique=True, max_length=250, unique_for_date='published')
    body = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    published = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(choices=Status.choices, default=Status.DRAFT, max_length=2)
    tags=TaggableManager()
    objects = models.Manager()
    publish = PublishedManager()

    class Meta:
        ordering = ['-published']
        indexes = [
            models.Index(fields=['-published'])
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.published.year, self.published.month, self.published.day,
                                                 self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=250)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

mysite/blog/forms.py
from django import forms

from blog.models import Comment


class EmailForm(forms.Form):
    name = forms.CharField(max_length=25, required=True, widget=forms.TextInput(attrs={"class": "form-control mb-1", 'placeholder': 'Name'}))
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={"class": "form-control mb-1", 'placeholder': 'E-Mail'}))
    to = forms.EmailField(required=True, widget=forms.TextInput(attrs={"class": "form-control mb-1", 'placeholder': 'To'}))
    comments = forms.CharField(required=False,
                               widget=forms.Textarea(attrs={"class": "form-control mb-1", 'placeholder': 'Comments'}))

class CommentForm(forms.ModelForm):
    name = forms.CharField(required=True,
                           widget=forms.TextInput(attrs={"class": "form-control", 'placeholder': 'Name'}))
    email = forms.EmailField(required=True,
                             widget=forms.EmailInput(attrs={"class": "form-control", 'placeholder': 'Email'}))
    body = forms.CharField(required=True, widget=forms.Textarea(attrs={"class": "form-control", 'placeholder': 'Text'}))

    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']


class SearchForm(forms.Form):
    query = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control mb-1", 'placeholder': 'Enter search term...'}))

mysite/blog/views.py
from django.contrib.auth.models import User
from django.contrib.postgres.search import TrigramSimilarity, TrigramWordSimilarity
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from django.views.generic import ListView
from django.db.models import Count
from blog.forms import EmailForm, CommentForm, SearchForm
from blog.models import Post
from taggit.models import Tag
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from mysite import settings


def post_list(request, tag_slug=None):
    posts = Post.publish.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = Post.objects.filter(tags=tag)
    paginator = Paginator(posts, 3)  # 1-что раскидать на стр, 2-кол-во объектов на стр
    page_number = request.GET.get('page', 1)  # 1-всегда, 2- параметр по умолчанию, в случ. отст.
    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)  # num_pages-последняя страница
    return render(request, 'blog/post/list.html', {'posts': page_obj, 'tag': tag, })


def post_detail(request, year, month, day, slug):
    post = get_object_or_404(Post,
                             status=Post.Status.PUBLISHED,
                             slug=slug,
                             published__year=year,
                             published__month=month,
                             published__day=day)
    comments = post.comments.filter(active=True)
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.publish.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', 'published')[:4]
    form = CommentForm()
    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'form': form,
                   'similar_posts': similar_posts})

#не надо
class PostListView(ListView):
    queryset = Post.publish.all()
    paginate_by = 3
    context_object_name = 'posts'
    template_name = 'blog/post/list.html'


def share_post(request, post_id):
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED, id=post_id)
    sent = False
    if request.method == 'POST':
        form = EmailForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            link_on_post = request.build_absolute_uri(post.get_absolute_url())
            subject = f'{cd['name']} recommends you to read {post.title}'
            message = f"Read {post.title} at {link_on_post}\n\n" \
                      f"{cd['name']} ({cd['email']}) comments: {cd['comments']}"
            send_mail(subject, message, settings.EMAIL_HOST_USER, [cd['to']])
            sent = True
    else:
        form = EmailForm()
    return render(request, 'blog/post/email.html', {'post': post, 'form': form, 'sent': sent})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment_post=request.POST.copy() #делаем копию,которую сможет изменять т.к объект QueryDict является неизменяемым
    if request.user.is_authenticated:
        comment_post['name'] = request.user.username #добавл имя и почту в копию данных post запроса
        comment_post['email'] = request.user.email
    form = CommentForm(data=comment_post)#отправл классический пост запрос, но уже с почтой и именем
    comment = None
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(request, 'blog/post/comment.html', {'post': post, 'form': form, 'comment': comment})


def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET: #Триграммный поиск
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']  # стремминг-преобразование слова к словообраз. форме
            A = 1.0                             # Триграмма – это группа из трех следующих друг за другом символов
            B = 0.4
            results = Post.publish.annotate(
                similarity=(A / (A + B) * TrigramSimilarity('title', query)
                            + B / (A + B) * TrigramWordSimilarity(query, 'body'))
            ).filter(similarity__gte=0.1).order_by('-similarity')
    return render(request,
                  'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

#не используется пока что
def user_total_posts(request,user_id=None):
    total_posts = Post.publish.count()
    user=None
    if user_id:
        user=get_object_or_404(User, id=user_id)
        total_posts=user.blog_posts.count()
    return render(request,'blog/base.html',{'total_posts':total_posts,'user':user})

mysite/templates/blog/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    {% load django_bootstrap5 %}
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    
</head>
<body class="d-flex flex-column min-vh-100">
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'blog:post_list' %}">My First Blog Django 5</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:profile' %}"><img
                            class="rounded-circle" width="30" src="{{ user.profile.avatar.url }}"/> {{ user.username }}
                    </a></li>
                    <li class="nav-item">
                        <form action="{% url 'accounts:logout' %}" method="post">{% csrf_token %}
                            <a href="#" class="nav-link" onclick="parentNode.submit();">Log Out</a>
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<!-- Page content-->
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
            {% if messages %}
                {% for message in messages %}
                    <div class="container d-flex align-items-center justify-content-center">
                        <div class="alert alert-warning alert-dismissible fade show w-50  d-block" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}

            {% block content %}
            {% endblock %}
        </div>
        <!-- Widgets-->
        <div class="col-lg-4">
            <div class="card mb-4">
                <div class="card-header">This is my blog.</div>
                <div class="card-body">
                    Total posts {% total_posts %} so far.
                </div>
            </div>
            <!-- Search widget-->
            <div class="card mb-4">
                <div class="card-header">Search</div>
                <div class="card-body">
                    <div class="input-group">
                        <form action="{% url 'blog:post_search' %}" method="get" class="input-group">
                            <input type="text" name="query" class="form-control" placeholder="Enter search term..."
                                   required="" id="id_query">
                            <button class="btn btn-primary" id="button-search" type="submit">Go!</button>
                        </form>
                    </div>
                </div>
            </div>
            <!-- Latest posts widget-->
            <div class="card mb-4">
                <div class="list-group">
                    <a class="list-group-item list-group-item-action active" aria-current="true">
                        Latest posts
                    </a>
                    {% show_latest_posts 3 %}
                </div>
            </div>
            <div class="card mb-4">
                <div class="list-group">
                    <a class="list-group-item list-group-item-action active" aria-current="true">
                        Most commented posts
                    </a>
                    {% get_most_commented_posts as most_commented_posts %}
                    {% for post in most_commented_posts %}
                        <a class="list-group-item list-group-item-action"
                           href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer-->
<footer class="py-5 bg-dark mt-2 mt-auto">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2024, Powered by
        Django</p></div>
</footer>
<script defer src="{% static 'js/bootstrap.js' %}" ></script>

</body>
</html>

mysite/templates/blog/pagination.html
<div class="pagination p-3">
        {% if page.has_previous %}
            <a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <a class="page-link disabled">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.</a>

        {% if page.has_next %}
            <a class="page-link" href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
</div>